#!/bin/bash

# Add packages
pip install gdal=="$(gdal-config --version)" --install-option="build_ext" --install-option="$(gdal-config --cflags | sed 's/-I/--include-dirs=/')"
pip install fiona --install-option="build_ext" --install-option="$(gdal-config --cflags | sed 's/-I/--include-dirs=/')"
pip install pyproj
pip install geopandas
pip install rasterio
pip install pyviz_comms
pip install bokeh
pip install param
pip install holoviews
pip install pyct
pip install panel
pip install parambokeh
pip install datashader
pip install descartes
pip install seaborn
pip install salem
pip install git+https://github.com/OGGM/oggm.git
pip install git+https://github.com/OGGM/oggm-edu.git
pip install git+https://github.com/retostauffer/python-colorspace

# Jupyterlab
pip install jupyterlab==0.35.4
pip install ipympl
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
jupyter labextension install jupyterlab_bokeh
jupyter labextension install @pyviz/jupyterlab_pyviz

# Add funny font
mkdir ~/.fonts
wget http://antiyawn.com/uploads/Humor-Sans-1.0.ttf
mv Humor-Sans-1.0.ttf ~/.fonts/Humor-Sans-1.0.ttf
cd ~/.fonts/
fc-cache -f -v

# Back to home
cd ~

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
test -e test.png && rm test.png

# Set up OGGM paths
mkdir .oggm_cache
rm -f .oggm_config
echo "dl_cache_dir = $HOME/.oggm_cache/download_cache" >> .oggm_config
echo "dl_cache_readonly = False" >> .oggm_config
echo "tmp_dir = $HOME/.oggm_cache/tmp" >> .oggm_config
echo "cru_dir = $HOME/.oggm_cache/cru" >> .oggm_config
echo "rgi_dir = $HOME/.oggm_cache/rgi" >> .oggm_config
echo "test_dir = $HOME/.oggm_cache/OGGM_tests" >> .oggm_config
echo "has_internet = True" >> .oggm_config

# Get the OGGM data
python binder/download_cache.py
