#!/bin/bash

# Add packages
pip install gdal=="$(gdal-config --version)" --install-option="build_ext" --install-option="$(gdal-config --cflags | sed 's/-I/--include-dirs=/')"
pip install fiona --install-option="build_ext" --install-option="$(gdal-config --cflags | sed 's/-I/--include-dirs=/')"
pip install pyproj
pip install geopandas
pip install rasterio
pip install pyviz_comms
pip install bokeh
pip install param
pip install holoviews
pip install pyct
pip install panel
pip install parambokeh
pip install datashader
pip install descartes
pip install salem
pip install git+https://github.com/OGGM/oggm.git

# Add funny fint
mkdir ~/.fonts
wget http://antiyawn.com/uploads/Humor-Sans-1.0.ttf
mv Humor-Sans-1.0.ttf ~/.fonts/Humor-Sans-1.0.ttf
cd ~/.fonts/
fc-cache -f -v

# Back to home
cd ~

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
test -e test.png && rm test.png

# Get the OGGM data
python binder/download_cache.py
