#!/bin/bash
pip install pyviz_comms
pip install bokeh
pip install param
pip install holoviews
pip install pyct
pip install panel
pip install parambokeh
pip install datashader

mkdir ~/.fonts
wget http://antiyawn.com/uploads/Humor-Sans-1.0.ttf
mv Humor-Sans-1.0.ttf ~/.fonts/Humor-Sans-1.0.ttf
cd ~/.fonts/
fc-cache -f -v

# Back to home
cd ~

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

# Get the OGGM data
python binder/download_cache.py
